name: CD

on:
  push:
    branches:
      - master
      - ci

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Le test
        uses: Badrpas/gh-pages-index-compiler@v0.1
